name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      - name: Run PHPUnit
        run: |
          php -v
          php -m
          phpunit --version || true
          sudo apt-get update
          sudo apt-get install -y phpunit
          phpunit --configuration tests/phpunit.xml
